- request:
    method: GET
    url: /api/v1/hello
  response:
    status: 200
    headers:
      content-type: application/json; charset=utf-8
    file: ./json/hello/resposne_happy_1.json
- request:
    method: POST
    headers:
      content-type: application/json
    url: /api/v1/hello
  response:
    status: 200
    headers:
      content-type: application/json; charset=utf-8
    file: ./json/hello/resposne_happy_2.json